server:
  port: 3344



spring:
   application:
     name:  springcloud-config
   cloud:
     config:
       server:
         git:
           uri: https://github.com/Lesliexiaokeai/config/ #GitHub上面的git仓库名字
           username: jiexin.wu@accenture.com
           password: jie1015..+
           search-paths:
             -
       label: master